name: Go

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read

jobs:
  call-workflow:
    uses: ./.github/workflows/build-library.yml
